### ISSUE TITLE
Generating an expression matrix at single-cell resolution

### ISSUE THREAD

**Issue by jleechung** [linnarsson-lab/FISHscale#23]
In the [preprint for EEL FISH ](https://www.biorxiv.org/content/10.1101/2022.01.12.476082v1) there is a section describing the generation of an expression matrix for 128,813 single cells and 440 genes (line ~280) for a sagittal section of the mouse brain. 

Is this processed expression matrix available for download anywhere, or is there any documentation on how to obtain this matrix with FISHscale?  

Thanks!

**Comment by larsborm** [comment]
Hi @jleechung, All data is now available on [Figshare](https://figshare.com/projects/Scalable_in_situ_single-cell_profiling_by_electrophoretic_capture_of_mRNA_using_EEL_FISH/143616)

The code to generate these files is included in the image analysis pipeline: https://github.com/linnarsson-lab/pysmFISH_auto
